### ISSUE TITLE
java.lang.ClassNotFoundException: pl.xayanix.bbce.bungee.BringBackChatEdit

### ISSUE THREAD

**Issue by DominikSLK** [Xayanix/BringBackChatEdit#1]
[09:46:01 WARN]: Error loading plugin BringBackChatEdit
java.lang.ClassNotFoundException: pl.xayanix.bbce.bungee.BringBackChatEdit
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:103) ~[waterfall-1.19-496.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:ab3ccb8:496]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59) ~[waterfall-1.19-496.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:ab3ccb8:496]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:394) ~[waterfall-1.19-496.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:ab3ccb8:496]
        at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:300) ~[waterfall-1.19-496.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:ab3ccb8:496]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:278) ~[waterfall-1.19-496.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:ab3ccb8:496]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[waterfall-1.19-496.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:ab3ccb8:496]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[waterfall-1.19-496.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:ab3ccb8:496]

**Comment by Xayanix** [comment]
Fixed in https://github.com/Xayanix/BringBackChatEdit/commit/2a5fe8296ae5c7bb26e4bea89fd26ec1c1c91a92
